#!/usr/bin/env bash

#  /$$$$$$$$ /$$      /$$ /$$   /$$ /$$   /$$        /$$$$$$                               /$$                     /$$
# |__  $$__/| $$$    /$$$| $$  | $$| $$  / $$       /$$__  $$                             |__/                    |__/
#    | $$   | $$$$  /$$$$| $$  | $$|  $$/ $$/      | $$  \__/  /$$$$$$   /$$$$$$$ /$$$$$$$ /$$  /$$$$$$  /$$$$$$$  /$$ /$$$$$$$$  /$$$$$$   /$$$$$$
#    | $$   | $$ $$/$$ $$| $$  | $$ \  $$$$/       |  $$$$$$  /$$__  $$ /$$_____//$$_____/| $$ /$$__  $$| $$__  $$| $$|____ /$$/ /$$__  $$ /$$__  $$
#    | $$   | $$  $$$| $$| $$  | $$  >$$  $$        \____  $$| $$$$$$$$|  $$$$$$|  $$$$$$ | $$| $$  \ $$| $$  \ $$| $$   /$$$$/ | $$$$$$$$| $$  \__/
#    | $$   | $$\  $ | $$| $$  | $$ /$$/\  $$       /$$  \ $$| $$_____/ \____  $$\____  $$| $$| $$  | $$| $$  | $$| $$  /$$__/  | $$_____/| $$
#    | $$   | $$ \/  | $$|  $$$$$$/| $$  \ $$      |  $$$$$$/|  $$$$$$$ /$$$$$$$//$$$$$$$/| $$|  $$$$$$/| $$  | $$| $$ /$$$$$$$$|  $$$$$$$| $$
#    |__/   |__/     |__/ \______/ |__/  |__/       \______/  \_______/|_______/|_______/ |__/ \______/ |__/  |__/|__/|________/ \_______/|__/
#
# Auther: mnjm (github.com/mnjm)
# Repo: github.com/mnjm/tmux-sessionizer
# License: MIT

LIST_FILE=${TMUX_SEZ_LIST_FILE:-"$HOME/.tmux-sessionizer.list"}
FZF_COMMAND=${TMUX_SEZ_FZF_COMMAND:-"fzf --height 100%"}
[ -f "$LIST_FILE" ] || touch $LIST_FILE # Create list file if doesnt exists

display_help() {
    echo "TMUX Sessionizer - fzf based tmux session/project switcher"
    echo "For more info check https://github.com/mnjm/tmux-sessionizer/blob/main/README.md"
}

# List tmux session names with color codes
list_sessions() {
    local cur_sess=""
    [ -v TMUX ] && cur_sess=$(tmux display-message -p "#S")
    tmux list-sessions -F "#{session_name}" 2>> /dev/null | while read sess; do
        if [[ $sess != $cur_sess ]]; then
            echo -e "\e[32m${sess}\e[0m"
        fi
    done
}

# List entries in $LIST_FILE with color codes
list_file_entries() {
    cat $LIST_FILE 2>> /dev/null | while read entry; do
        local name="${entry%% *}"
        # Removes duplicates whose session already exists.
        if ! tmux has-session -t $name 2>/dev/null; then
            echo -e "\e[34m${entry}\e[0m"
        fi
    done
}

# tmux session switcher
switch() {
    local sessions=$(list_sessions)
    local file_entries=$(list_file_entries)
    [ ! -z "$sessions" ] && [ ! -z "$file_entries" ] && sessions="${sessions}\n"

    local selected=$( echo -e "$sessions$file_entries" | $FZF_COMMAND \
        --reverse --no-multi --print-query --delimiter=' ' --with-nth=1 --ansi \
        --preview "tmux-sessionizer __preview__ {}" --preview-window right,80% | tail -n1 )

    local name="${selected%% *}"
    local path="${selected#* }"
    [ -z $path ] && path="$HOME"

    # create / switch to selected session
    if [[ -n $selected ]]; then
        if [[ -z "$TMUX" ]]; then # if tmux is not running
            tmux new -As $name -c $path
        else
            if  ! tmux has-session -t $name 2>/dev/null; then # if session not found
                tmux new -ds $name -c $path
            fi
            tmux switch-client -t $name
        fi
    fi
}

# preview for entries, if it is a session then capture-pane else list dir contents
tmux_sessionzier_previewer() {
    # function reserved to be called as fzf previewer
    local name="${1%% *}"
    local path="${1#* }"
    if tmux has-session -t $name 2>/dev/null; then
        tmux capture-pane -e -pt $name
    else
        echo -e "Session Name: \e[4m\e[34m$name\e[0m"
        echo -e "Dir: \e[35m$path\e[0m"
        echo "-----------------------------------------------"
        ls --group-directories-first --color=always "$path"
    fi
}

# remove duplicates and deleted dirs, replace . in session names with _
sanitize_list_file() {
    echo "Sanitizing $LIST_FILE"

    # go through each entry - sanitize session name and remove non reachable entries
    local tmp_file=$(mktemp tms.XXXXX -p /tmp/)
    cat $LIST_FILE | while read line; do
        local name="${line%% *}"
        local path="${line#* }"
        # . and ' ' doesnt work in session_name, replace with _
        name=$(echo $name | sed -E 's/(\\? |\.)/_/g')
        if [ -d "$path" ]; then
            echo "$name $path" >> $tmp_file
        else
            >&2 echo "Removing $name: $path not reachable"
        fi
    done

    # Removing duplicate entries
    gawk -i inplace '!seen[$1]++' $tmp_file

    # update file only if there's changes
    if [[ $(diff $LIST_FILE $tmp_file | wc -l) -eq 0 ]]; then
        rm $tmp_file
    else
        mv $LIST_FILE $LIST_FILE.old
        mv $tmp_file $LIST_FILE
        echo "Updated ${LIST_FILE}, old file can be found in ${LIST_FILE}.old"
    fi
}

# adds an entry into $LIST_FILE
add_to_list_file() {
    local path=$1
    local name=$2

    if [ -z "$path" ]; then
        path="$PWD"
    else
        if [ ! -d "$path" ]; then
            >&2 echo "Error: $path is not a directory"
            return 12
        fi
        path=$(realpath "$path")
    fi
    [ -z "$2" ] && name=$(basename "$path")

    # . and ' ' doesnt work in session_name, replace with _
    name=$(echo $name | sed -E 's/(\\? |\.)/_/g')

    # add a new entry to LIST_FILE
    echo "$name $path" >> $LIST_FILE
    echo "Added $name -> $path to $LIST_FILE"

    sanitize_list_file
}

# open list file in editor
edit_list_file() {
    ${EDITOR:-vim} $LIST_FILE
    sanitize_list_file
}

case $1 in
    add) add_to_list_file "$2" "$3" ;;
    switch) switch ;;
    sanitize) sanitize_list_file ;;
    edit) edit_list_file ;;
    __preview__) tmux_sessionzier_previewer "$2" ;;
    *) display_help ;;
esac
